// This is embed code generated by remarkbox

var rb_owner_key = "{{comments}}";
var thread_uri = window.location.href;
var thread_title = window.document.title;
var thread_fragment = window.location.hash;

// rb owner was here.
var rb_src = "https://my.remarkbox.com/embed" + 
    "?rb_owner_key=" + rb_owner_key +
    "&thread_title=" + encodeURI(thread_title) +
    "&thread_uri=" + encodeURIComponent(thread_uri) + 
    thread_fragment;

function create_remarkbox_iframe() {
    var ifrm = document.createElement("iframe");
    ifrm.setAttribute("id", "remarkbox-iframe");
    ifrm.setAttribute("scrolling", "no");
    ifrm.setAttribute("src", rb_src);
    ifrm.setAttribute("frameborder", "0");
    ifrm.setAttribute("tabindex", "0");
    ifrm.setAttribute("title", "Remarkbox");
    ifrm.style.width = "100%";
    document.getElementById("remarkbox-div").appendChild(ifrm);
}
create_remarkbox_iframe();
iFrameResize(
    {
	checkOrigin: ["https://my.remarkbox.com"],
	inPageLinks: true,
	initCallback: function(e) {e.iFrameResizer.moveToAnchor(thread_fragment)}
    },
    document.getElementById("remarkbox-iframe")
);
