* OH MY FUCKING GOD FIX THIS
The ids for blocks within a page are not stable, making links to them broken... what idiot wrote this? Come up with a plan to fix

* Search bug
DONE "operators" does not turn up the page https://hyperphor.com/ammdi/__Operators-and-Things__
Maybe title isn't getting processed, or its a function of the italic markup?
Confirmed: the search index's :title field used the raw page title (markup and all,
eg "__Operators and Things__"), which broke elasticlunr tokenization and also meant
the page had no plain-text rendering of its own title anywhere in the index. Fixed
by stripping markup via a new goddinpotty.rendering/plain-title before indexing.


* AskClaude popups
DONE Looks like ass in sidebar, needs to be hidden.


* Collapsed panes
use either the LogSeq flag or #AskClaude (customizable)

* Deploy should track commits or branches or something.
And there should be a diff view (at least on github)

* 2026

** Arxiv links don't render properly eg
[[1001.2485v2] Physics With Two Time Dimensions](https://arxiv.org/abs/1001.2485v2) (!)
on Jacon Foster page

** DONE BUG Weird Materialism has link to [[Weirding [[Dennett]]]] which is hidden evn though page exists and is published. (actually condense all these tiny pages, should have a macro for that)
The page-link grammar rule (resources/parser.ebnf) was #"\[\[.*?\]\]", non-greedy, so it
stopped at the *first* "]]" it found. For a title that itself contains a page link, eg
"Weirding [[Dennett]]", that meant "[[Weirding [[Dennett]]]]" parsed as page-link
"[[Weirding [[Dennett]]" (missing its close) plus stray literal "]] " text -- the mangled
title then failed to resolve to the real page, so it rendered as excluded/missing
(rendering.clj's page-link, the [:span.empty ...] branch) even though the page exists and
is published. Fixed by making the regex accept one level of nested [[...]] (same fix
applied to the #[[...]] hashtag form, which has the identical issue). See
goddinpotty.parser-test/nested-page-link-test.

** TODO Logseq HTML includes not supported (permission-structure)
** TODO a j page is getting published for some reason (Mar 4 2022)

* Post Bergson Course

** DONE full map completely not working (file missing)

** TODO #Privatize or other more sane way to flag
(I already did this but forgot details) (apparently not, just fatansized)

** TODO aliases should render, maybe filtering out stupid ones (case/punc only)

** TODO bug where link titles contain [] (eg, from arxiv.org.)


** Print support / have a mode that hides left column and expands main.
I suppose that LH col hiding should be sticky, its something someone might just not want.

** DONE make page links look more distinctive (could still be better though)

* Post Prot Sym

** DONE Add og: metadata for Discord previews (sigh)
https://stackoverflow.com/questions/62438757/how-to-make-a-link-preview-for-discord


* Post CDD
** Bug in bold rendering on Protocols/Ideas page
** John Gray – not clear why it is published, and why is the map empty?
*** OH wait I think all the maps are broken

** MORE BROADLY
needs a lot of rethinking, nibbling at the edges has become tedious


* The perpetual lag problem

See here
https://github.com/logseq/nbb-logseq/issues/1
C-x C-s in logseq saves the current graph, see if that is decent. But really we should be



* 11 Aug 2023 [[Weirding [[Dennett]]]] not rendering title properly, link is strikethrough, I bet I know why.




Against Narrativity - Zotero link to @Against Narrativity goes to same page!!!
  Also @Against page looks like shit, the properties need to be rendered or something.
   Or possibly those pages should be excluded, they don't look like they are supposed to be very human-readable.




Yes this should be and mostly is in Logseq. This si for small local coding stuff

New pages after tweaking page-empty?

OK, now aliases are working but not showing up in search. FUCK.



Pages that should be aliases
ammdi/Ainslie (prob in source, fixed)
ammdi/Crowley
ammdi/The-Society-of-Mind


New empty pages that are now included
ammdi/Andy-Matuschak
ammdi/Brian-Cantwell-Smith
ammdi/Catch-22

New real pages



New pages but not sure why
ammdi/Annhilation (only one incoming link)

that are really tags:
ammdi/Article
ammdi/Attachments (generated by Zotero and useless)
ammdi/Bug

Checked



Raw

ammdi/Ainslie
ammdi/Andy-Matuschak
ammdi/Annhilation
ammdi/Article
ammdi/Attachments
ammdi/Brian-Cantwell-Smith
ammdi/Bug
ammdi/Catch-22
ammdi/Charles-Taylor
ammdi/Cinema-Purgatorio

ammdi/Dōgen
ammdi/Everything-Everywhere-All-at-Once
ammdi/Finnegans-Wake
ammdi/Fredrich-Schiller
ammdi/GOFAI
ammdi/Generative-art
ammdi/Gideon-the-Ninth
ammdi/Heraclitus
ammdi/His-Dark-Materials

ammdi/MIT-Media-Lab
ammdi/McLuhan
ammdi/Meillassoux
ammdi/Northrop-Frye
ammdi/Pragmatism
ammdi/Promethea
ammdi/Red-Plenty
ammdi/Religion-Explained
ammdi/Rokos-Basilisk
ammdi/Seeing-Like-a-State
ammdi/Seymour-Papert
ammdi/Southern-Reach-trilogy
ammdi/Tao-Te-Ching
ammdi/The-Second-Self

ammdi/ToSelf
ammdi/Twin-Peaks
ammdi/Walter-Ong
ammdi/Whitehead
ammdi/Wu-Wei
ammdi/animacy
ammdi/antiphilosophy
ammdi/author
ammdi/graphics
ammdi/green-links
ammdi/hypertext
ammdi/identity
ammdi/movie
ammdi/nebulous
ammdi/nondualim
ammdi/nondualism
ammdi/notes
ammdi/omniorthogonal
ammdi/paper
ammdi/psychoanlysis
ammdi/representationalism
ammdi/review
ammdi/structure-of-feeling
ammdi/tulpa
ammdi/tv

